security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: ROLE_ADMIN }
        - { path: ^/api/users/create, roles: ROLE_ADMIN }
        - { path: ^/api/users/\d+, roles: ROLE_ADMIN }
        - { path: ^/api/user/\d+, roles: ROLE_ADMIN }
        - { path: ^/api/conges/create, roles: ROLE_USER }
        - { path: ^/api/conges, roles: ROLE_ADMIN }
        - { path: ^/api/conges/\d+, roles: ROLE_ADMIN }
        - { path: ^/api/conge/\d+, roles: ROLE_USER }
        - { path: ^/api/commentaire/create, roles: ROLE_USER }
        - { path: ^/api/commentaire/\d+, roles: ROLE_USER }
        - { path: ^/api/commentaire/edit/\d+, roles: ROLE_USER }
        - { path: ^/api/reponse/admin/\d+, roles: ROLE_ADMIN }
        - { path: ^/api/label, roles: ROLE_ADMIN }
        - { path: ^/api/label/\d+, roles: ROLE_ADMIN }
        - { path: ^/api/label/edit/\d+, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
