# config/services.yaml
parameters:
    # Vous pouvez définir ici vos propres paramètres
    locale: 'en'

services:
    # Service par défaut : enregistre les services dans src/
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # Si vous avez des classes spécifiques que vous voulez auto-enregistrer :
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Configuration des services spécifiques
    App\Service\NotificationService:
        arguments:
            $mailer: '@mailer'  # Injecter le service mailer
            $logger: '@logger'  # Injecter le logger
        public: true  # Facultatif si tu souhaites rendre ce service accessible publiquement

    # Ajouter vos services ici
    # Exemple d'un service custom
    App\EventSubscriber\ExceptionSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    # Import des services dans un sous-dossier
    _defaults:
        autowire: true      # Automatiquement injecter les dépendances
        autoconfigure: true # Automatiquement enregistrer les événements et les services
        public: false       # Les services ne sont pas accessibles publiquement par défaut
